name: GitHub-Actions-Bot-Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # ഓരോ 15 മിനിറ്റിലും ബോട്ട് സ്റ്റാറ്റസ് ചെക്ക് ചെയ്യാനും റീസ്റ്റാർട്ട് ചെയ്യാനും
    - cron: '*/15 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Running The Bot
      # 350 മിനിറ്റ് (ഏകദേശം 6 മണിക്കൂർ) കഴിയുമ്പോൾ ബോട്ട് തനിയെ സേഫ് ആയി നിൽക്കാൻ
      timeout-minutes: 350
      run: python3 bot.py
